### ISSUE TITLE
Attempted another video fail

### ISSUE THREAD

**Issue by iaytutu1** [jguoaj/multi-object-tracking#2]
Hello, your example worked for me.Appreciated.  However, when I try to use another video from internet,  I got the error below. Do you have any idea ? 
Thank you.

2019-03-27 13:13:25.757307: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
fps= 0.143811
fps= 6.322116
**Traceback (most recent call last):
  File "tracking.py", line 226, in <module>
    main(YOLO())
  File "tracking.py", line 111, in main
    newXs, newYs = estimateAllTranslation(startXs, startYs, oldframe, frame)
  File "/home/iaytutu1/workspace/multi-object-tracking/optical_flow/estimateAllTranslation.py", line 25, in estimateAllTranslation
    newXs[i], newYs[i] = estimateFeatureTranslation(startXs_flat[i], startYs_flat[i], Ix, Iy, img1, img2)
  File "/home/iaytutu1/workspace/multi-object-tracking/optical_flow/estimateFeatureTranslation.py", line 89, in estimateFeatureTranslation
    solution = np.linalg.solve(A, b)
  File "/home/iaytutu1/.local/lib/python3.5/site-packages/numpy/linalg/linalg.py", line 403, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
  File "/home/iaytutu1/.local/lib/python3.5/site-packages/numpy/linalg/linalg.py", line 97, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix**

**Comment by iaytutu1** [comment]
I solved the problem by setting capture to next frames, thanks anyway.
